src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $commentAuthor = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $commentText = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Posts $post = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\Column]
    private ?int $voteScore = 0;

    #[ORM\OneToMany(targetEntity: Vote::class, mappedBy: 'comment', orphanRemoval: true)]
    private Collection $votes;

    public function __construct()
    {
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentAuthor(): ?string
    {
        return $this->commentAuthor;
    }

    public function setCommentAuthor(string $commentAuthor): static
    {
        $this->commentAuthor = $commentAuthor;

        return $this;
    }

    public function getCommentText(): ?string
    {
        return $this->commentText;
    }

    public function setCommentText(string $commentText): static
    {
        $this->commentText = $commentText;

        return $this;
    }

    public function getPost(): ?Posts
    {
        return $this->post;
    }

    public function setPost(?Posts $post): static
    {
        $this->post = $post;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getVoteScore(): ?int
    {
        return $this->voteScore;
    }

    public function setVotes(int $voteScore): static
    {
        $this->voteScore = $voteScore;

        return $this;
    }

//    public function upvote(): void
//    {
//        $this->voteScore++;
//
//    }
//
//    public function downvote(): void
//    {
//        $this->voteScore--;
//    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVotes(Vote $votes): static
    {
        if (!$this->votes->contains($votes)) {
            $this->votes->add($votes);
            $votes->setComment($this);
        }

        return $this;
    }

    public function removeVotes(Vote $votes): static
    {
        if ($this->votes->removeElement($votes)) {
            // set the owning side to null (unless already changed)
            if ($votes->getComment() === $this) {
                $votes->setComment(null);
            }
        }

        return $this;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToMany(targetEntity: Posts::class, mappedBy: 'user', orphanRemoval: true)] // Use 'user' here
    private Collection $posts;

    #[ORM\Column(length: 20)]
    private ?string $username = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageFileName = null;

    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'user')]
    private Collection $comments;

    #[ORM\Column]
    private ?int $post_count = null;

    #[ORM\Column]
    private ?int $comment_count = null;

    #[ORM\OneToMany(targetEntity: Follow::class, mappedBy: 'followedUserId')]
    private Collection $followedBy;

    #[ORM\OneToMany(targetEntity: Follow::class, mappedBy: 'followerUserId')]
    private Collection $following;

    #[ORM\OneToMany(targetEntity: Rating::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $ratings;

    #[ORM\OneToMany(targetEntity: Vote::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $votes;

    #[ORM\OneToMany(targetEntity: Like::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $likes;

    #[ORM\OneToMany(targetEntity: View::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $views;



    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();

        $this->followedBy = new ArrayCollection();
        $this->following = new ArrayCollection();
        $this->ratings = new ArrayCollection();
        $this->votes = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->views = new ArrayCollection();




    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string)$this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Posts>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Posts $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Posts $post): static
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getImageFileName(): ?string
    {
        return $this->imageFileName;
    }

    public function getImagePath(): string
    {
        return 'uploads/profile_image/' . $this->getImageFileName();
    }

    public function setImageFileName(?string $imageFileName): static
    {
        $this->imageFileName = $imageFileName;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function getPostCount(): ?int
    {
        return $this->post_count;
    }

    public function setPostCount(int $post_count): static
    {
        $this->post_count = $post_count;

        return $this;
    }

    public function getCommentCount(): ?int
    {
        return $this->comment_count;
    }

    public function setCommentCount(int $comment_count): static
    {
        $this->comment_count = $comment_count;

        return $this;
    }

    public function getFollowedBy(): Collection
    {
        return $this->followedBy;
    }

    public function setFollowedBy(Collection $followedBy): void
    {
        $this->followedBy = $followedBy;
    }

    public function getFollowing(): Collection
    {
        return $this->following;
    }

    public function setFollowing(Collection $following): void
    {
        $this->following = $following;
    }


    public function addFollowedBy(User $user): static
    {
        if (!$this->followedBy->contains($user)) {
            $this->followedBy->add($user);

        }

        return $this;
    }

    public function removeFollowedBy(User $user): static
    {
        $this->followedBy->removeElement($user);
        return $this;
    }


    public function addFollowing(User $user): static
    {
        if (!$this->following->contains($user)) {
            $this->following->add($user);

        }

        return $this;
    }

    public function removeFollowing(User $user): static
    {
        $this->following->removeElement($user);
        return $this;
    }

    /**
     * @return Collection<int, Rating>
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): static
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings->add($rating);
            $rating->setUser($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): static
    {
        if ($this->ratings->removeElement($rating)) {
            // set the owning side to null (unless already changed)
            if ($rating->getUser() === $this) {
                $rating->setUser(null);
            }
        }

        return $this;
    }



    public function toArray()
    {
        return[
            'post_count' => $this->post_count,
            'comment_count' => $this->comment_count,

        ];



    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): static
    {
        if (!$this->votes->contains($vote)) {
            $this->votes->add($vote);
            $vote->setUser($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): static
    {
        if ($this->votes->removeElement($vote)) {
            // set the owning side to null (unless already changed)
            if ($vote->getUser() === $this) {
                $vote->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)

src/Entity/Vote.php
<?php

namespace App\Entity;

use App\Repository\VoteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoteRepository::class)]
class Vote
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'votes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'votes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Comment $comment = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $vote_type = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getComment(): ?Comment
    {
        return $this->comment;
    }

    public function setComment(?Comment $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getVoteType(): ?int
    {
        return $this->vote_type;
    }

    public function setVoteType(int $vote_type): static
    {
        $this->vote_type = $vote_type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }
}

templates/post/create.html.twig
{% extends "base.html.twig" %}


{% block body %}
    {{ form_start(PostFormType) }}
        <div class="post-main">
            {{ form_row(PostFormType.title) }}
            {{ form_row(PostFormType.text) }}
{#            <a>{{ post.date }}</a>#}
            {{ form_row(PostFormType.submit) }}
        </div>
    {{ form_end(PostFormType) }}
{% endblock %}

templates/post/followingPosts.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="following-post-page-container">
        <div class="page-title-home">
            <h1>Posts from Following Users</h1>
        </div>

        <div class="post-filter-button-container">
            <a class="post-filter-button" href="{{ path('post-page') }}"> All Posts</a>
            <a class="post-filter-button" href="{{ path('/following-posts') }}"> Following</a>
        </div>

        <div class="following-post-main">
            {% for post in followingPosts %}
                <div class="post">

                    <a class="inspect-link" href="{{ path('inspect-post', { 'id': post.id }) }}">
                        <div class="title-data">{{ post.title }}</div>
                    </a>

                    <div class="text-data">{{ post.text }}</div>

                    {% set likedPostIds = likes|map(like => like.post.id) %}
                    <div class="like-container">
                        <a class="like" href="{{ path('like-post', {'id': post.id}) }}" data-id="{{ post.id }}" data-like-state="{{ post.id in likedPostIds ? 'true' : 'false' }}">
                            <i class="fa-regular fa-heart"></i>
                        </a>
                        <div class="total-likes">{{ post.totalLikes}}</div>
                    </div>


                    {% set userRating = 0 %}
                    {% for rating in userRatings %}
                        {% if rating.post.id == post.id %}
                            {% set userRating = rating.score %}
                        {% endif %}
                    {% endfor %}

                    <a class="rating-text">Rate this post!</a>
                    <div class="ratings" data-user-rating="{{ userRating }}">
                        <div class="rating-button-container">
                            <a class="rating-button" data-value="1" data-id="{{ post.id }}">
                                <i class="{{ userRating >= 1 ? 'fa-solid fa-star' : 'fa-regular fa-star' }}"></i>
                            </a>
                            <a class="rating-button" data-value="2" data-id="{{ post.id }}">
                                <i class="{{ userRating >= 2 ? 'fa-solid fa-star' : 'fa-regular fa-star' }}"></i>
                            </a>
                            <a class="rating-button" data-value="3" data-id="{{ post.id }}">
                                <i class="{{ userRating >= 3 ? 'fa-solid fa-star' : 'fa-regular fa-star' }}"></i>
                            </a>
                            <a class="rating-button" data-value="4" data-id="{{ post.id }}">
                                <i class="{{ userRating >= 4 ? 'fa-solid fa-star' : 'fa-regular fa-star' }}"></i>
                            </a>
                            <a class="rating-button" data-value="5" data-id="{{ post.id }}">
                                <i class="{{ userRating >= 5 ? 'fa-solid fa-star' : 'fa-regular fa-star' }}"></i>
                            </a>
                        </div>
                    </div>

                    <div class="home-post-footer">
                        <a class="home-post-date">{{ post.date|date('d-m-Y') }}</a>
                        <div class="popup">
                            <a>Posts: {{ post.user.postCount }}</a>
                            <a>Comments: {{ post.user.commentCount }}</a>
                        </div>
                        <div class="homePostedBy">{{ post.user.username }}</div>
                    </div>

                </div>
            {% else %}
                <p>No posts available.</p>
            {% endfor %}


        </div>

    </div>

{% endblock %}

templates/post/inspect.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    


<div class="inspect-container">
    <div class="inspect-post-container">

        <a class="inspect-back-button" href="{{ path('post-page') }}"> BACK </a>




        <div class="inspect-post">

            <div class="title-data">{{ post.title }}</div>
            <div class="text-data">{{ post.text }}</div>

            <form action="{{ path('follow_user', {'id': post.user.id}) }}" method="POST">
                <button type="submit">Follow</button>
            </form>

            {% set likedPostIds = likes|map(like => like.post.id) %}

            <div class="like-container">
                <a class="like" href="{{ path('like-post', {'id': post.id}) }}" data-id="{{ post.id }}" data-like-state="{{ post.id in likedPostIds ? 'true' : 'false' }}">
                    <i class="fa-regular fa-heart"></i>
                </a>
                <div class="total-likes">{{ post.totalLikes}}</div>

                <div class="views">
                    <i class="fa-regular fa-eye"></i>
                    {{ post.totalViews }}
                </div>
            </div>

            {% set userRating = 0 %}

            {% for rating in userRatings %}
                {% if rating.post.id == post.id %}

                    {% set userRating = rating.score %}

                {% endif %}
            {% endfor %}

            <div class="inspect-rating">
                <div class="ratings">
                    <div class="rating-button-container">

                        {% set fullStars = post.averageRating|round(0, 'floor') %}
                        {% set hasHalfStar = post.averageRating != fullStars %}

                        {% for i in 1..5 %}
                            {% if i <= fullStars %}
                                <i class="fas fa-star"></i>

                            {% elseif i == fullStars + 1 and hasHalfStar %}
                                <i class="fas fa-star-half-alt"></i>

                            {% else %}
                                <i class="far fa-star"></i>

                            {% endif %}
                        {% endfor %}
                        <span>Average rating: {{ post.averageRating|number_format(1) }}</span>
                    </div>
                </div>
            </div>



            <div class="myposts-footer">

                <a class="inspect-post-date">{{ post.date|date("d-m-Y") }}</a>
                <div class="postedBy">{{ post.user.username }}</div>


            </div>

        </div>
    </div>

    <div class="full-comment-container">
        <div class="comment-form-container">

            <form action="{{ path('postComment', {'id': post.id}) }}" method="post">

                <textarea class="comment-input" name="commentText" placeholder=" Enter your comment here..." required autocomplete="off"></textarea>
                <button class="comment-submit" type="submit">Submit</button>
            </form>

        </div>
        <div class="posted-comments-container">
            {% if post.comments is empty %}
                <p>No comments yet.</p>
            {% else %}
                {% for comment in post.comments|reverse %}


                    <div class="comment-data">

                        <div class="comment-container">

                            <div class="comment-profile-picture">
                                {% if comment.user.imageFileName is not null %}
                                    <img src="{{ asset(comment.user.imagePath) }}" alt="Profile Picture">
                                {% else %}
                                    <img src="{{ asset('uploads/profile_image/default.jpg') }}" alt="default picture">
                                {% endif %}
                            </div>

                            <div class="comment-username">{{ comment.commentAuthor }}</div>
                            <div class="comment-date">Posted {{ comment.createdAt| ago }}</div>

                            {% if comment.updatedAt is null %}

                            {% else %}
                                <div class="comment-edit-date">
                                    *edited {{ comment.updatedAt| ago }}*
                                </div>

                            {% endif %}

                            {% if app.user and app.user.username == comment.commentAuthor %}
                                <form action="{{ path('edit-post-comments', {'id': comment.id}) }}" method="post">
                                    <button class="edit-comment-button">edit</button>
                                </form>

                                <form action="{{ path('delete-comment', {'id': comment.id}) }}" method="post">
                                    <button class="edit-comment-button">Delete</button>
                                </form>



                            {% endif %}

                            {% set voteUp = false %}
                            {% set voteDown = false %}

                            {% for vote in votesByUser %}
                                {% if vote.comment.id == comment.id %}
                                    {% if vote.voteType == 1 %}
                                        {% set voteUp = true %}
                                    {% elseif vote.voteType == 0 %}
                                        {% set voteDown = true %}
                                    {% endif %}
                                {% endif %}
                            {% endfor %}

                            <div class="vote-container">

                                <form action="{{ path('vote', {'id': comment.id, 'voteType': 1}) }}" method="post" class="vote-form">
                                    <button class="vote-button {% if voteUp %} voted {% endif %}" data-value="1" data-id="{{ comment.id }}" type="submit">
                                        <i class="fa-solid fa-arrow-up"></i>
                                    </button>
                                </form>

                                <form action="{{ path('vote', {'id':comment.id, 'voteType': 0}) }}" method="post" class="vote-form">
                                    <button class="vote-button {% if voteDown %} voted {% endif %}" data-value="0" data-id="{{ comment.id }}" type="submit">
                                        <i class="fa-solid fa-arrow-down"></i>
                                    </button>
                                </form>

                            </div>


                            <span class="vote-count" data-id="{{ comment.id }}">{{ comment.voteScore }}</span>

                        </div>

                        <div class="comment-box">{{ comment.commentText }}</div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        </div>






</div>

{% endblock %}

templates/post/postpage.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}

    <script src="{{ asset('js/postpage.js') }}"></script>

{% endblock %}


{% block body %}




        <div class="postpage-container">
{#            <div class="page-title-home">#}
{#                <h1>POSTS</h1>#}
{#            </div>#}

            <div class="posts-header">
                <div class="search-bar">
                    <form id="search-form" action="{{ path('searched-posts') }}" method="post">
                        <input class="search-input" type="text" name="searchInput" placeholder="Search posts...">
                        <button type="submit">Search</button>
                    </form>
                </div>
                <div class="post-filter-button-container">
                    <a class="post-filter-button" href="{{ path('post-page') }}"> All Posts</a>
                    <a class="post-filter-button" id="following-button" href="{{ path('following-posts') }}"> Following</a>
                    <a class="post-filter-button" id="most-liked-button" href="{{ path('post-page') }}"> Most Liked</a>
                </div>

            </div>



            <div class="post-main" id="posts-container">
                {% set likedPostIds = likes|map(like => like.post.id) %}

                <script>
                    const likedPostIds = {{ likedPostIds|json_encode }};
                </script>
                {% for post in allPosts %}
                    <div class="post">

                        <a class="inspect-link" href="{{ path('inspect-post', { 'id': post.id }) }}">
                            <div class="title-data">{{ post.title }}</div>
                        </a>

                        <div class="text-data">{{ post.text }}</div>



                        <div class="like-container">
                            <a class="like" href="{{ path('like-post', {'id': post.id}) }}" data-id="{{ post.id }}" data-like-state="{{ post.id in likedPostIds ? 'true' : 'false' }}">
                                <i class="fa-regular fa-heart"></i>
                            </a>
                            <div class="total-likes">{{ post.totalLikes}}</div>

                            <div class="views">
                                <i class="fa-regular fa-eye"></i>
                                {{ post.totalViews }}
                            </div>
                        </div>


                        {% set userRating = 0 %}
                        {% for rating in userRatings %}
                            {% if rating.post.id == post.id %}
                                {% set userRating = rating.score %}
                            {% endif %}
                        {% endfor %}

                        <a class="rating-text">Rate this post!</a>
                        <div class="ratings" data-user-rating="{{ userRating }}">
                            <div class="rating-button-container">
                                <a class="rating-button" data-value="1" data-id="{{ post.id }}">
                                    <i class="{{ userRating >= 1 ? 'fa-solid fa-star' : 'fa-regular fa-star' }}"></i>
                                </a>
                                <a class="rating-button" data-value="2" data-id="{{ post.id }}">
                                    <i class="{{ userRating >= 2 ? 'fa-solid fa-star' : 'fa-regular fa-star' }}"></i>
                                </a>
                                <a class="rating-button" data-value="3" data-id="{{ post.id }}">
                                    <i class="{{ userRating >= 3 ? 'fa-solid fa-star' : 'fa-regular fa-star' }}"></i>
                                </a>
                                <a class="rating-button" data-value="4" data-id="{{ post.id }}">
                                    <i class="{{ userRating >= 4 ? 'fa-solid fa-star' : 'fa-regular fa-star' }}"></i>
                                </a>
                                <a class="rating-button" data-value="5" data-id="{{ post.id }}">
                                    <i class="{{ userRating >= 5 ? 'fa-solid fa-star' : 'fa-regular fa-star' }}"></i>
                                </a>
                            </div>
                        </div>

                        <div class="home-post-footer">
                            <a class="home-post-date">{{ post.date|date("d m Y")}}</a>
                            <div class="popup">
                                <a>Posts: {{ post.user.postCount }}</a>
                                <a>Comments: {{ post.user.commentCount }}</a>
                            </div>
                            <div class="homePostedBy">{{ post.user.username }}</div>
                        </div>

                    </div>
                    {% else %}
                    <p>No posts available.</p>
                {% endfor %}
            </div>
        </div>







{% endblock %}